---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-env-secret
  namespace: ci
stringData:
  # choose one of username/password or auth token
  ARGOCD_USERNAME: admin
  ARGOCD_PASSWORD: <<CHANGE_ME>>
#  ARGOCD_AUTH_TOKEN: <token>