apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/
patches:
  - patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: discounts
        labels:
          deployment: discounts
      spec:
        replicas: 2
