apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: pull-request-pipeline-triggertemplate
spec:
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: pull-request-pipelinerun-
      spec:
        pipelineRef:
          name: pull-request-pipeline
        params:
          - name: source-repo
            value: $(tt.params.source-repo)
          - name: revision
            value: $(tt.params.revision)
          - name: pr_id
            value: $(tt.params.pr_id)
        workspaces:
          - name: source-folder
            persistentVolumeClaim:
              claimName: workspace-pvc-source-folder     
          - name: diff-result
            persistentVolumeClaim:
              claimName: workspace-pvc-diff-result
  params:
    - name: source-repo
    - name: revision
    - name: pr_id