apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: show-pr-comment
spec:
  params:
    - name: BITBUCKET_TOKEN
      description: "The token to access Bitbucket API"
      type: string
    - name: PR_ID
      description: "The ID of the Pull Request"
      type: string
    - name: REPO_OWNER
      description: "The owner of the repository"
      type: string
    - name: REPO_SLUG
      description: "The slug of the repository"
      type: string
  steps:
    - name: fetch-pr-comment
      image: curlimages/curl:latest
      script: |
        #!/bin/sh
        echo "Fetching comments for PR $PR_ID from $REPO_OWNER/$REPO_SLUG"
        response=$(curl -s -H "Authorization: Bearer $(params.BITBUCKET_TOKEN)" \
          "https://api.bitbucket.org/2.0/repositories/$(params.REPO_OWNER)/$(params.REPO_SLUG)/pullrequests/$(params.PR_ID)/comments")
        echo "Response: $response"
        comments=$(echo $response | jq '.values[] | .content.raw')
        echo "PR Comments: $comments"
