---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-env-secret
  namespace: openshift-gitops 
stringData:
  # choose one of username/password or auth token
  # ARGOCD_USERNAME: {{ .Values.argocd.user }}
  # ARGOCD_PASSWORD: {{ .Values.argocd.pass }}
  ARGOCD_AUTH_TOKEN: {{ .Values.argocd.token }}