apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pull-request-pipeline
  namespace: ci  
spec:
  params:
  - name: source-repo
    description: A workspace that contains the fetched git repository.    
    type: string
  - name: revision
    description: the revision to sync to
    default: HEAD
    type: string
  - name: pr_id
    description: Pullrequest ID
    type: string
    default: '1'
  - name: repo_full_name
    type: string
    default: 'repo-full-name'
  workspaces:
  - name: source-folder  
  - name: diff-result


  tasks:

  - name: git-diff
    taskRef:
      name: git-cli
      kind: ClusterTask
    params:
      - name: GIT_SCRIPT
        value: |
          rm -rf repository
          git config --global --add safe.directory /workspace/source 
          git clone $(params.source-repo) repository
          cd repository
          git checkout $(params.revision)
          rm -f git-diff.txt
          git diff --name-only main..$(params.revision) > git-diff.txt

          pwd
          ls -la git-diff.txt
          cat git-diff.txt
    workspaces:
    - name: source
      workspace: source-folder

  - name: argocd-task-diff
    runAfter:
    - git-diff  
    taskRef:
      kind: Task
      name: argocd-task-diff
    params:
    - name: revision
      value: $(params.revision)
    workspaces:
    - name: source
      workspace: source-folder
    - name: diff-result
      workspace: diff-result

  - name: add-pr-comment
    runAfter:
    - argocd-task-diff
    taskSpec:
      metadata: {}
      params:
        - name: pr_id
          type: string
          default: '1'
        - name: repo_full_name
          type: string
          default: 'repo-full-name'
      steps:
      - name: set-results
        image: registry.access.redhat.com/ubi8/ubi-minimal:8.3
        env:
          - name: TOKEN
            valueFrom:
              secretKeyRef:
                name: repo-access-token-secret
                key: token
        resources: {}
        script: |
          #!/usr/bin/env bash

          pr_id=$(params.pr_id)
          comment_content=$(< $(workspaces.source-folder.path)/repository/git-diff.txt)
          repo_full_name=$(params.repo_full_name)
          access_token="$TOKEN";

          echo "Adding diff to PR ID '${pr_id}', comment: ${comment_content}";

          curl -X POST -H "Authorization: Bearer ${access_token}" \
            -H "Content-Type: application/json" \
            -d '{"content": {"raw": "Diff result: '"${comment_content}"'"}}' \
            "https://api.bitbucket.org/2.0/repositories/${repo_full_name}/pullrequests/${pr_id}/comments" 

      spec: null
    workspaces:
    - name: diff-result
      workspace: diff-result
    - name: source-folder
      workspace: source-folder

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: ci
  name: workspace-pvc-diff-result
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: ci
  name: workspace-pvc-source-folder
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi