apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pull-request-pipeline
  namespace: openshift-gitops   
spec:
  params:
  - name: source-repo
    description: A workspace that contains the fetched git repository.    
    type: string
  - name: revision
    description: the revision to sync to
    default: HEAD
    type: string
  workspaces:
  - name: source-folder  
  - name: diff-result


  tasks:


  - name: argocd-task-diff
    taskRef:
      kind: Task
      name: argocd-task-diff
    params:
    - name: revision
      value: $(params.revision)
    workspaces:
    - name: source
      workspace: source-folder
    - name: diff-result
      workspace: diff-result

  #TODO New task that update the PR with the contento of $(workspaces.diff-result.path)/diff-output.txt

  - name: see-diff-result
    runAfter:
    - argocd-task-diff
    taskSpec:
      metadata: {}
      steps:
      - name: set-results
        image: registry.access.redhat.com/ubi8/ubi-minimal:8.3
        resources: {}
        script: |
          #!/usr/bin/env bash
          cat $(workspaces.diff-result.path)/diff-output.txt 2>/dev/null || { echo 'There are not ArgoCD differences '; }
      spec: null
      workspaces:
      - name: diff-result
    workspaces:
    - name: diff-result
      workspace: diff-result
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: openshift-gitops 
  name: workspace-pvc-diff-result
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: openshift-gitops 
  name: workspace-pvc-source-folder
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi