apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: pull-request-pipeline-eventlistener
  namespace: ci
spec:
  triggers:
    - name: pull-request-pipeline-trigger
      bindings:
        - ref: pull-request-pipeline-triggerbinding
      template:
        ref: pull-request-pipeline-triggertemplate
  serviceAccountName: pipeline

