apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: "true"
  name: el-pull-request-pipeline
  namespace: ci
spec:
  host: el-pull-request-pipeline-eventlistener-ci.apps.cluster-49lc7.dynamic.redhatworkshops.io
  # host: change_me
  port:
    targetPort: 8080
  to:
    kind: Service
    name: el-pull-request-pipeline-eventlistener
    weight: 100
  wildcardPolicy: None
