apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: argocd-task-diff
  namespace: ci  
spec:
  workspaces:
    - name: diff-result
    - name: source 
  params:
    - name: revision
      description: the revision to sync to
      default: HEAD
      type: string
    - name: flags
      default: --
      type: string
    - name: argocd-version
      default: v2.2.2 
      type: string
  stepTemplate:
    envFrom:
      - configMapRef:
          name: argocd-env-configmap  # used for server address
      - secretRef:
          name: argocd-env-secret  # used for authentication (username/password or auth token)
  steps:
    - name: diff
      image: quay.io/argoproj/argocd:$(params.argocd-version)
      #TODO from git-diff.txt get all the application-name
      #TODO manage when argocd app diff return error
      script: |
        cat $(workspaces.source.path)/repository/git-diff.txt
        application="ocp-pro-01-discounts"
        if [ -z "$ARGOCD_AUTH_TOKEN" ]; then
          yes | argocd login "$ARGOCD_SERVER" --username="$ARGOCD_USERNAME" --password="$ARGOCD_PASSWORD";
        fi
        set +e
        argocd app diff $application --revision "$(params.revision)" "$(params.flags)" > $(workspaces.diff-result.path)/diff-output.txt 2>&1
        status=$?
        cat $(workspaces.diff-result.path)/diff-output.txt
        if [ $status -eq 0 ] 
        then 
          echo "No diff is found" 
          exit 0
        else 
          echo "Diff is found" >&2 
          exit 0
        fi