# tekton-triggers-admin-rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-triggers-admin-binding
subjects:
  - kind: ServiceAccount
    name: tekton-triggers-admin
    namespace: telefonica
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io

