apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.namePrefix }}discounts
  labels:
    deployment: discounts
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        deployment: discounts
        app: demo
    spec:
      containers:
        - name: discounts
          image: quay.io/dseveria/discounts:v1.0.1
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          envFrom:
          - configMapRef:
              name: {{ .Values.namePrefix }}discounts-configmap-env-base
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          resources: {}


