apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-service-account
---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: service-account-validation-
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    metadata:
      name: service-account-validation
    spec:
      serviceAccountName: my-service-account
      containers:
      - name: validation-container
        image: registry.access.redhat.com/ubi8/ubi-minimal
        command: ["sh", "-c", "echo 'Service Account is working!'"]
      restartPolicy: Never
  backoffLimit: 2
