apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.namePrefix }}discounts
  labels:
    deployment: discounts
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    deployment: {{ .Values.namePrefix }}discounts
  type: ClusterIP
