---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset-discounts-kustomize
  namespace: openshift-gitops
spec:
  generators:
  - git:
      repoURL: https://github.com/davidseve/argocd-example-application.git
      revision: HEAD
      files:
      - path: "cluster-definition/**/cluster.json"
  #syncPolicy:
  #  preserveResourcesOnDeletion: true
  template:
    metadata:
      name: '{{cluster.alias}}-discounts-kustomize'
      namespace: openshift-gitops
    spec:
      destination:
        name: ''
        namespace: openshift-gitops
        server: '{{cluster.address}}'
      source:
        path: discounts-kutomize/overlays/{{cluster.name}}
        repoURL: https://github.com/davidseve/argocd-example-application.git
        targetRevision: HEAD
      project: default