---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset-discounts-helm
  namespace: openshift-gitops
spec:
  generators:
  - git:
      repoURL: https://github.com/davidseve/argocd-example-application.git
      revision: HEAD
      files:
      - path: "cluster-definition/**/cluster.json"
  #syncPolicy:
  #  preserveResourcesOnDeletion: true
  template:
    metadata:
      name: '{{cluster.alias}}-discounts-helm'
      namespace: openshift-gitops
      labels: 
        app-config: discounts-helm
        cloud: '{{cloud}}'
    spec:
      destination:
        name: ''
        namespace: openshift-gitops
        server: '{{cluster.address}}'
      source:
        repoURL: https://github.com/davidseve/argocd-example-application.git
        targetRevision: HEAD
        path: ./discounts-helm 
        helm: 
          valueFiles: 
            - values.yaml 
            - clusters/values-{{cluster.alias}}.yaml           
      project: default
      syncPolicy:      
        retry:
          limit: 5 # number of failed sync attempt retries; unlimited number of attempts if less than 0
          backoff:
            duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
            factor: 2 # a factor to multiply the base duration after each failed retry
            maxDuration: 1m