# hello-world-eventlistener.yaml
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  # name: hello-world-eventlistener
  name: pipeline-validacion-eventlistener
spec:
  triggers:
    # - name: hello-world-trigger
    - name: pipeline-validacion-trigger
      bindings:
        # - ref: hello-world-triggerbinding
        - ref: pipeline-validacion-triggerbinding
      template:
        # ref: hello-world-triggertemplate
        ref: pipeline-validacion-triggertemplate
  serviceAccountName: tekton-triggers-admin

