apiVersion: v1
kind: ConfigMap
metadata:
  name: discounts-configmap-env-base
  labels:
    deployment: discounts  
data:
  application.version: v1.0.1
  application.colour: black
  quarkus.log.level: debug
  application.mode: other

