apiVersion: v1
kind: Service
metadata:
  name: discounts
  labels:
    deployment: discounts
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    deployment: discounts
  type: ClusterIP
